version: '3.8'

services:
  mysql:
    image: ${DOCKER_USERNAME}/mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: ${DOCKER_USERNAME}/backend:latest
    container_name: backend_container
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - mynetwork
    ports:
      - "8080:8080"

  nginx:
    image: ${DOCKER_USERNAME}/nginx:latest
    container_name: nginx_container
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data: